name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        id: set_scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "default=$default" >> $GITHUB_ENV
          echo "Using default scheme: $default"

      - name: Build
        run: |
          scheme="${{ env.default }}"
          if [ -z "$scheme" ]; then
            echo "Default scheme is not set"
            exit 1
          fi
          filetype_parameter=""
          file_to_build=""
          if [ "$(ls -A | grep -i \\.xcworkspace\$)" ]; then 
            filetype_parameter="workspace"
            file_to_build=$(ls -A | grep -i \\.xcworkspace\$)
          elif [ "$(ls -A | grep -i \\.xcodeproj\$)" ]; then
            filetype_parameter="project"
            file_to_build=$(ls -A | grep -i \\.xcodeproj\$)
          else
            echo "No Xcode workspace or project file found"
            exit 1
          fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          destination="platform=macOS,arch=arm64,variant=Designed for iPad"
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "$destination" | xcpretty && exit ${PIPESTATUS[0]}
